services:
  api:
    container_name: go_backend_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: go_backend
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - postgres_network
  db:
    container_name: go_backend_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_backend
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:7.4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: yetkinzuleyha94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - db

networks:
  postgres_network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres:
  api_volume: