version: '3.8'

services:
  api:
    container_name: go_backend_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - postgres_network
    volumes:
      - api_volume:/app

  db:
    container_name: go_backend_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:7.4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: yetkinzuleyha94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - db

  rabbitmq:
    container_name: go_backend_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres:
  api_volume:
  rabbitmq-data:
